<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625082917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE club_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) DEFAULT \'Notre histoire\' NOT NULL, founding_year INT DEFAULT 1991 NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tarif (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(30) NOT NULL, label VARCHAR(120) NOT NULL, price NUMERIC(6, 2) NOT NULL, featured BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE club_history');
        $this->addSql('DROP TABLE tarif');
    }
}
